USE bank;
CREATE TABLE txn_details
(txn_no INT UNIQUE AUTO_INCREMENT PRIMARY KEY NOT NULL,
acc_no INT NOT NULL,
name VARCHAR(100) NOT NULL,
Credit_Debit ENUM('Credit','Debit') NOT NULL,
amount FLOAT NOT NULL,
balance FLOAT NOT NULL,
txn_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

SELECT * FROM txn_details;