CREATE DATABASE IF NOT EXISTS bank;
USE bank;
CREATE TABLE holder
(acc_no INT UNIQUE PRIMARY KEY NOT NULL AUTO_INCREMENT,
acc_type ENUM ('Saving_account','Current_account') NOT NULL,
name VARCHAR(100) NOT NULL,
pan_no VARCHAR(10) UNIQUE NOT NULL,
age INT NOT NULL,
gender ENUM('Male','Female','Other') NOT NULL,
phone_no VARCHAR(10) UNIQUE NOT NULL,
email_id VARCHAR(255) NOT NULL,
balance FLOAT NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
hashed_pin VARCHAR(255)
);
ALTER TABLE holder AUTO_INCREMENT = 1000;

SELECT * FROM holder;



